export const filterData = [
  {
    age: "15",
    name: "Aang",
    bender: "yes",
    nation: "Air",
    person: "yes",
    show: "ATLA",
  },
  {
    age: "20",
    name: "Appa",
    bender: "yes",
    nation: "Air",
    person: "no",
    show: "ATLA",
  },
  {
    age: "10",
    name: "Asami",
    bender: "no",
    nation: "Republic City",
    person: "yes",
    show: "LOK",
  },
  {
    age: "15",
    name: "Azula",
    bender: "yes",
    nation: "Fire",
    person: "yes",
    show: "ATLA",
  },
  {
    age: "25",
    name: "Bolin",
    bender: "yes",
    nation: "Earth",
    person: "yes",
    show: "LOK",
  },
  {
    age: "5",
    name: "Katara",
    bender: "yes",
    nation: "Water",
    person: "yes",
    show: "ATLA",
  },
  {
    age: "10",
    name: "Korra",
    bender: "yes",
    nation: "Water",
    person: "yes",
    show: "LOK",
  },
  {
    age: "15",
    name: "Jinora",
    bender: "yes",
    nation: "Air",
    person: "yes",
    show: "LOK",
  },
  {
    age: "15",
    name: "Lin Beifong",
    bender: "yes",
    nation: "Republic City",
    person: "yes",
    show: "LOK",
  },
  {
    age: "10",
    name: "Pabu",
    bender: "no",
    nation: "Fire",
    person: "no",
    show: "LOK",
  },
  {
    age: "5",
    name: "Momo",
    bender: "no",
    nation: "Air",
    person: "no",
    show: "ATLA",
  },
  {
    age: "20",
    name: "Mai",
    bender: "no",
    nation: "Fire",
    person: "yes",
    show: "ATLA",
  },
  {
    age: "30",
    name: "Mako",
    bender: "yes",
    nation: "Fire",
    person: "yes",
    show: "LOK",
  },
  {
    age: "35",
    name: "Naga",
    bender: "no",
    nation: "Water",
    person: "no",
    show: "LOK",
  },
  {
    age: "35",
    name: "Sokka",
    bender: "no",
    nation: "Water",
    person: "yes",
    show: "ATLA",
  },
  {
    age: "30",
    name: "Suki",
    bender: "no",
    nation: "Earth",
    person: "yes",
    show: "ATLA",
  },
  {
    age: "10",
    name: "Tenzin",
    bender: "yes",
    nation: "Air",
    person: "yes",
    show: "LOK",
  },
  {
    age: "15",
    name: "Toph Beifong",
    bender: "yes",
    nation: "Earth",
    person: "yes",
    show: "ATLA",
  },
  {
    age: "20",
    name: "Ty Lee",
    bender: "no",
    nation: "Fire",
    person: "yes",
    show: "ATLA",
  },
  {
    age: "20",
    name: "Uncle Iroh",
    bender: "yes",
    nation: "Fire",
    person: "yes",
    show: "ATLA",
  },
  {
    age: "15",
    name: "Varrick",
    bender: "no",
    nation: "Republic City",
    person: "yes",
    show: "LOK",
  },
  {
    age: "20",
    name: "Zhu Li",
    bender: "no",
    nation: "Republic City",
    person: "yes",
    show: "LOK",
  },
  {
    age: "10",
    name: "Zuko",
    bender: "yes",
    nation: "Fire",
    person: "yes",
    show: "ATLA",
  },
];
